apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  clusterIP: None
  ports:
  - port: 2281
    name: client-tls
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    app: zookeeper
