scheduler:
  config: |-
    [zookeeper]
    hosts=zookeeper-0.zookeeper:2281
    tls_cert=/cert/client.pem
    tls_key=/cert/clientkey.pem
    tls_ca=/cert/cacert.pem

    [gearman]
    server=zuul-scheduler-0.zuul-scheduler

    [gearman_server]
    start=true

    [scheduler]
    tenant_config=/tenants/main.yaml

    [connection "github"]
    driver=github
    app_id=89996
    app_key=/etc/github/github.key
    webhook_token=%(ZUUL_GITHUB_WEBHOOK_TOKEN)s

    [connection "opendev"]
    driver=git
    baseurl=https://opendev.org/

    [database]
    dburi=mysql+pymysql://zuul:%(ZUUL_MYSQL_PASSWORD)s@mysql-0.mysql/zuul

    [web]
    root=https://zuul.vassast.org
    listen_address=0.0.0.0
  tenants: |-
    - tenant:
        name: vassast
        exclude-unprotected-branches: true
        report-build-page: true
        source:
          opendev:
            untrusted-projects:
              - zuul/zuul-jobs
          github:
            config-projects:
              - albinvass/zuul-config
            untrusted-projects:
              - albinvass/zuul-jobs
              - albinvass/hatty
              - albinvass/vinescore
              - albinvass/illwill
              - albinvass/zuul
              - dhackz/wurg:
                  exclude-unprotected-branches: false
executor:
  image: ghcr.io/albinvass/zuul-executor:nossh
  imagePullPolicy: Always
  config: |-
    [zookeeper]
    hosts=zookeeper-0.zookeeper:2281
    tls_cert=/cert/client.pem
    tls_key=/cert/clientkey.pem
    tls_ca=/cert/cacert.pem

    [connection "github"]
    driver=github
    app_id=89996
    app_key=/etc/github/github.key
    webhook_token=%(ZUUL_GITHUB_WEBHOOK_TOKEN)s

    [connection "opendev"]
    driver=git
    baseurl=https://opendev.org/

    [gearman]
    server=zuul-scheduler-0.zuul-scheduler
web:
  config: |-
    [zookeeper]
    hosts=zookeeper-0.zookeeper:2281
    tls_cert=/cert/client.pem
    tls_key=/cert/clientkey.pem
    tls_ca=/cert/cacert.pem

    [connection "github"]
    driver=github
    app_id=89996
    app_key=/etc/github/github.key
    webhook_token=%(ZUUL_GITHUB_WEBHOOK_TOKEN)s

    [database]
    dburi=mysql+pymysql://zuul:%(ZUUL_MYSQL_PASSWORD)s@mysql-0.mysql/zuul

    [gearman]
    server=zuul-scheduler-0.zuul-scheduler

    [web]
    root=https://zuul.vassast.org
    listen_address=0.0.0.0
launcher:
  config: |-
    zookeeper-servers:
      - host: zookeeper-0.zookeeper
        port: 2281
    zookeeper-tls:
      cert: /cert/client.pem
      key: /cert/clientkey.pem
      ca: /cert/cacert.pem
    labels:
      - name: alpine-pod
      - name: fedora-pod
    providers:
      - name: kubernetes-digitalocean
        driver: kubernetes
        pools:
          - name: main
            labels:
              - name: alpine-pod
                type: pod
                image: ghcr.io/albinvass/alpine-python:latest
                image-pull: Always
              - name: fedora-pod
                type: pod
                image: ghcr.io/albinvass/fedora-python:latest
                image-pull: Always
mysql:
  count: 1
zookeeper:
  count: 1
