scheduler:
  imagePullPolicy: Always
  #image: zuul/zuul-scheduler:4.1.0
  config: |-
    [statsd]
    server=statsd-0.statsd

    [zookeeper]
    hosts=zookeeper-0.zookeeper:2281
    tls_cert=/cert/client.pem
    tls_key=/cert/clientkey.pem
    tls_ca=/cert/cacert.pem

    [gearman]
    server=zuul-scheduler-0.zuul-scheduler

    [gearman_server]
    start=true

    [scheduler]
    tenant_config=/tenants/main.yaml

    [connection "github"]
    driver=github
    app_id=89996
    app_key=/etc/github/github.key
    webhook_token=%(ZUUL_GITHUB_WEBHOOK_TOKEN)s

    [connection "opendev"]
    driver=git
    baseurl=https://opendev.org/

    [database]
    dburi=mysql+pymysql://zuul:%(ZUUL_MYSQL_PASSWORD)s@mysql-0.mysql/zuul

    [web]
    root=https://zuul.vassast.org
    listen_address=0.0.0.0
  tenants: |-
    - tenant:
        name: vassast
        exclude-unprotected-branches: true
        report-build-page: true
        source:
          opendev:
            untrusted-projects:
              - zuul/zuul-jobs
          github:
            config-projects:
              - albinvass/zuul-config
            untrusted-projects:
              - albinvass/zuul-jobs
              - albinvass/hatty
              - albinvass/vinescore
              - albinvass/illwill
              - albinvass/zuul
              - albinvass/fedora-python
              - dhackz/wurg
              - dhackz/ci-images
executor:
  imagePullPolicy: Always
  #image: zuul/zuul-executor:4.1.0
  config: |-
    [statsd]
    server=statsd-0.statsd

    [zookeeper]
    hosts=zookeeper-0.zookeeper:2281
    tls_cert=/cert/client.pem
    tls_key=/cert/clientkey.pem
    tls_ca=/cert/cacert.pem

    [connection "github"]
    driver=github
    app_id=89996
    app_key=/etc/github/github.key
    webhook_token=%(ZUUL_GITHUB_WEBHOOK_TOKEN)s

    [connection "opendev"]
    driver=git
    baseurl=https://opendev.org/

    [executor]
    private_key_file=/var/ssh/zuul
    trusted_ro_paths=/var/ssh

    [gearman]
    server=zuul-scheduler-0.zuul-scheduler
web:
  imagePullPolicy: Always
  #image: zuul/zuul-web:4.1.0
  config: |-
    [statsd]
    server=statsd-0.statsd

    [zookeeper]
    hosts=zookeeper-0.zookeeper:2281
    tls_cert=/cert/client.pem
    tls_key=/cert/clientkey.pem
    tls_ca=/cert/cacert.pem

    [connection "github"]
    driver=github
    app_id=89996
    app_key=/etc/github/github.key
    webhook_token=%(ZUUL_GITHUB_WEBHOOK_TOKEN)s

    [database]
    dburi=mysql+pymysql://zuul:%(ZUUL_MYSQL_PASSWORD)s@mysql-0.mysql/zuul

    [gearman]
    server=zuul-scheduler-0.zuul-scheduler

    [web]
    root=https://zuul.vassast.org
    listen_address=0.0.0.0
launcher:
  image: ghcr.io/albinvass/nodepool-launcher
  imagePullPolicy: Always
  config: |-
    zookeeper-servers:
    - host: zookeeper-0.zookeeper
      port: 2281
    zookeeper-tls:
      cert: /cert/client.pem
      key: /cert/clientkey.pem
      ca: /cert/cacert.pem
    labels:
    - name: alpine-pod
    - name: fedora-pod
    - name: ubuntu-groovy
    - name: ubuntu-groovy-rust-1.47.0
    - name: ec2-t3-micro-ubuntu-20.04
    providers:
    - name: kubernetes-digitalocean
      driver: kubernetes
      pools:
      - name: main
        labels:
        - name: alpine-pod
          type: pod
          cpu: "1"
          memory: "500"
          image: ghcr.io/albinvass/alpine-python:latest
          image-pull: Always
        - name: fedora-pod
          type: pod
          cpu: "1"
          memory: "500"
          image: ghcr.io/albinvass/fedora-python:latest
          image-pull: Always
    - name: do-fra-1
      driver: digitalocean
      region: fra1
      cloud-images:
        - name: ubuntu-groovy
          username: zuul
          image-filter:
            id: 72067660
        - name: ubuntu-groovy-rust-1.47.0
          username: zuul
          image-filter:
            name: rust-1.47.0
            private: true
      pools:
        - name: main
          max-servers: 8
          labels:
            - name: ubuntu-groovy
              size: s-4vcpu-8gb
              cloud-image: ubuntu-groovy
              # Dummy key to stop digital ocean from spamming emails
              # about temporary root passwords.
              ssh-keys:
                - 28913272
              user-data: |
                #cloud-config

                users:
                  - name: zuul
                    sudo: ALL=(ALL) NOPASSWD:ALL
                    ssh_authorized_keys:
                      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDiMrbqfJf8c8MSne60fdxGTJQA1zLn67FRYxRZf6LeOjlUgQwZdrz8LA5f88BSzwm9uRh0mJTPwMKx0qe1fhuu9dy4GRGcL1Y2Rgg3IQqIScb0TyieLB+1J4EO5T+cFyPsh353p+7ZWq+/S0T5WtUB3VImGURwxzO6TvVaGnWs8HJtOsTQqmASBmIAVeN/f1lOK0jRg8MZji8LWU/LJzoH/+257Vhi8YpFe8G7W59cDW//h2ZwLtVdRvR1nYk4ZGyWKs9rh2RDOEslpOD0V1NMQgqB2YVd2Q13iKjqtO+EJKtX74jSe+xrpawOceULv9/3BOt+0eBKtjTkUTqPPo8maiarxzGsg+iuDYPPjYuwjJ61i4fADVMX7agBBX3t7f44rv1zTmdLGCzg+K5NqAue3fzP7EOozTlYL46+NLwBEOEFf75WQDp4GcCArS8oYxMrhSd/1na6HTYjtgiVyt+2xMR7jZns+9A+zuK614A4lH4eZKTc+nVUIHQ4mWkVi3s= avass@albin-xps159500
                      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIbUUscEm4IJeTxlEJF1HdsLdipLpgx7w4ntgEii4PD4QBpR/8F2KS8wV62Md7wSpdCNx5oT6h57cOAWKQYU6oFtSqakSc8ULuEK+0rSmPsz4aV0Kqp1wqkmG35iU59MMkKqjDCFuIXH9yRgb6Y1QyNF2D4ZQmHZQMzM97FGjMeEQY/w54b8Sswu+3lCjgRX9+lXH12kt+EPRglKH4FgTVy+Lgl3n60mr0pinZYAXfVRVIdqadBaJHySTsNWaphKQtx7Enw+mk50a0THy/6cNHy+sOCLLwGqyExAuuMyystwNg63jZJA09jfai2vBwWPPCb9+ai6n8lDScPiptbDg55aLQBVztKFWIg8pfXXHp4vLFBUxfx4vSjyawDBcEFc59nUk6/MQNsBpZvUBHqS/Z6XURx35u91MBOw3upTCcXfbJpDGcpaEdAUMhrwrC1BdYuTAs/VmJuGMAspSTLymWp8GPMHhXUDtqGRgFMdCho83PZJrlnLKVEQ6vqLLmwbU= zuul
            - name: ubuntu-groovy-rust-1.47.0
              size: s-4vcpu-8gb
              cloud-image: ubuntu-groovy-rust-1.47.0
              # Dummy key to stop digital ocean from spamming emails
              # about temporary root passwords.
              ssh-keys:
                - 28913272
    - name: aws-eu-north-1
      driver: aws
      region-name: eu-north-1
      security-group-id: sg-0bb000e185ea4a7bc
      subnet-id: subnet-0cddf50a540db74aa
      cloud-images:
      - name: ubuntu-20.04
        image-id: ami-0ed17ff3d78e74700
        username: ubuntu
      pools:
      - name: main
        security-group-id: sg-0bb000e185ea4a7bc
        subnet-id: subnet-0cddf50a540db74aa
        max-servers: 5
        labels:
        - name: ec2-t3-micro-ubuntu-20.04
          instance-type: t3.micro
          cloud-image: ubuntu-20.04
          key-name: zuul-ssh
mysql:
  count: 1
zookeeper:
  count: 1
