apiVersion: v1
kind: Service
metadata:
  name: statsd
  labels:
    app: statsd
spec:
  ports:
    - port: 80
      targetPort: graphite
      name: graphite
    - port: 8125
      targetPort: statsd
      name: statsd
  selector:
    app: statsd
