apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodepool-launcher
  labels:
    app: nodepool-launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodepool-launcher
  template:
    metadata:
      labels:
        app: nodepool-launcher
    spec:
      serviceAccountName: nodepool-launcher
      containers:
      - name: nodepool-launcher
        image: {{ .Values.launcher.image | quote }}
        imagePullPolicy: {{ .Values.launcher.imagePullPolicy | quote }}
        command: ["nodepool-launcher", "-d", "-f"]
        ports:
        - name: http
          containerPort: 8005
        volumeMounts:
        - name: nodepool-config
          mountPath: /etc/nodepool
        - name: zookeeper-tls
          mountPath: /cert/
        env:
        - name: STATSD_HOST
          value: statsd-0.statsd
        - name: STATSD_PORT
          value: "8125"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: nodepool-aws
              key: aws-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: nodepool-aws
              key: aws-secret-key
        - name: DIGITALOCEAN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: nodepool-digitalocean
              key: access-token
      volumes:
      - name: nodepool-config
        configMap:
          name: nodepool-config
      - name: zookeeper-tls
        secret:
          secretName: zookeeper-tls
