apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: {{ .Values.count }}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: var-lib-mysql-permissions
        image: busybox
        command: ["chown", "1000:1000", "-R", "/var/lib/mysql"]
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
        securityContext:
          runAsUser: 0
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: zuul-mysql
              key: database
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zuul-mysql
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: zuul-mysql
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zuul-mysql
              key: password
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
