apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nodepool-digitalocean
  namespace: zuul
spec:
  encryptedData:
    access-token: AgB5oLYFUbPuPB0b5DJp8H5XckGb+CXClPCC7r5no5/hVc3pmxyyj4Vxv8Zco3vXonM4p1FvFzV5v3uZldSmrWg+G4xKIeR487Q99pG+fGOuYqo6uT46j5GhmfvQTuaXpZsr2mfh1eb4WFcu05ixPha6yx4QQgQ9LRK2cODaV+C/xBIDRwgZTZXj3dZxVFv8aGTv5cTtYRWsquzwPxJoiZlxmQz9+p+YgTYaA+uuxYJFq8w3+QzmBtA4RS7ZVSoVZdVaF981BFBrvXnkaA7xbvWQFJXUwt6SXoxThVCR2WGOSUClzT3F+hcnumzXvJSwD/0DG2fJycuCW/NVpVd97oW3VmvpvUsRrngD1caMYRzkoKG0OsjmLGtIFQZm4qjeUJej+U2wKs4baqx4ve8Abarjlpyd3HRP29IjT8VIt0RYuvNi4tiD9Ue0pOP9LcloVDv1MyCgi+U4XPFDqfqQ+9LHXWoZgJE5NSH0hyVepJeBeACCXRdd+yxIQwc14gIYj96tR7HM2jI/vfqaJ7z631hipnVHdkBLysUZXMZQ/FzUVDLJGW8s4GKKhxIrwwO0ylPoEPbaffQgcS8BXYV0cCcCF75DU13mdfyS42lMkiFal9t/ghdEmGPk4Pd6JPlWTjLCKskivx0en4qeAlNhN4AyIvEBCoH4UDR8S5V6nEOvPXJaWi+w6GhdgEI+oAT6T8zPNwBXH+AnQa0G19mzdRgoTuUSy3UJh1agXN2V8ZLkpBt7DRSpPjtT277cZsr1MJ7ikMtuooxJbsmZ+Pdp5vPW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:access-token: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2021-03-22T19:23:22Z"
      name: nodepool-digitalocean
      namespace: zuul
    type: Opaque

