apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zuul-mysql
  namespace: zuul
spec:
  encryptedData:
    database: AgAwi4ET/KNqfckBBH48ouusgBecPpEyqmnmJXz4pvUrA0HWsjP/5kZA7XcF+y80RYT3w9ulMxwtGtWP8L8SxUqbAYmPHCqpLBfdGLc/5sAyKWZKxxkKK1/W2v9cz/boG+ijz1+siV7EK+zvIEgVkJMaRiVazjLgxjXfBHKoXNpvWSigo91naIlJqwcn/uYMNNUTJ5xydzqCe1xhPJyItBfRsWKHvFVijISvWX0zNqIpNPw7zo9BdYYfqYb7sIKOr1mTyQeH0GjqFyviOgYnzKdn3WbaZiIxl946Orh/xynhcIDXInSAJhGZkfDI17Toze+3KdCGPBnpKyxeRQgLBaotjGo/uw87/Ne6XMnai1gHVPAeKiB2pcClZD8B8KUiZGc5tNtSuct6/Z+79P+dFuEWpFS3iUmc6VulpqlGbygslH6b0ohktqbBSSCrZ9BdIFqd7h1PBz+m/zD0XKy4vR5n5N22hB/QR4ry0hwh5hbnl66yamSd3llkfbLXyuKT65g6TNuUTCHWGZoEksZkEAyc96M/pOcfj1OrSdv6F1CK9Yy74vwvBE1S5nd9yVDYfknT84NoeRbkmvfrTdyLbxtmr0Ah3kdWsUYkGO30ZXNwWlEZWtDeBieQX/t6h+BPNlaarCknmc6xz9PdbdXYEqjX2L7/G5+9FYez+r6Qf9vk8IcD39ov9Yuu3e8fAA3jtR4nZv/o
    password: AgBa1/0+01GUZyWgiabTepWpQkVlZRJPOQV4Nlbfooj1zrewQsplJQevuqzuOaC89zeDqPKblNEYM5Qct3CAyh9EMFAZuqmVkcdRAMRl1emkcoAtsFYVj2mFA5myzJFC9iUREgXipC6iJE5gZWRl+v4VZ9WhqdqqfuuICfzmmfRTCxGujS7lqhZv8/9uIaavTMG7xTNZleZhcJAI1Yz8biYGZRyTDxHaLV3afEhIdRjUiZK5pIItIEfG8Uwj8f1Vv101Nc2xl8er20IylPYqpgESmbC+TUdv96MtRbJrmbFS2LtITGrJPuphtR9dKkcJbweZ9Su/n/C4TOlYpk6iy0gwBIXEEpW0JbaRElYU7mxt+bJWh1Ltb9TRXYa985LybAdaevGs7sWC+4YJTPz1U6QiT6LURgbKeaJ+ge/UCxbto3uCg7HFoNmo5lrZvDlQz09dQXot0uZe95IwZ1AkKYWBtDfAzrIPEflFPIEPzDSlJwiQ+13ONiQV/2lkeUU2l4bKV5COtCb+fBYgg9BeUOg9j2huTx/qFYyyRENX5stdPqPEqvQjY2oy8AuSdUR5UbRkQwUIk45mgGdPjriZjlr9lkar+GT7zB7XVS3nUzECFI1SySelE7Qpix5tMaCpnirLEhTfBkFkQvJLK1RfQcwF3HKh9GtNytn5hM9RIl1rVXYUccmabf25EVK4vWcwj0tUiTyRDCshWiTMhazE6g==
    root-password: AgC6o/J5UT1UfnSx/b4m2IW8yID6rq3j3IlkUXLAPA6PCorgMwhgbHJiNx9o13fMdMSiXSixB0H8ej11Wi7ax40vpZFbeJ1y6P179zM/R8DWcXVCRiBWkJZZZPOXL8uu50AAjoC4bZ6gwBigN9hosZChcN3A3G9dTb0Wr+yuefISOR71p9NJQD8jpRbgPH8aDpvV4nzde3ga6eSdyO/JQHlqiCdWam4YyHiJcFRQ/rh6EoG1l12C+afjgzkNbR8+i8VRSYYfq0FaZmax7TxXh5yiTTPfaiXtx55bmxgZMhgRF9jiwL9cYqGtvvOSzt/N/Kl2pwnStem/yCYNyzPSQWsM0peHis6Po8hNocLz4jLm8jeStZu1gSOVFnLEdXzHoXfNguMRZ9r7migLIaabrZbAYb69PS5g7o1LBGCosLFCsXZ2tumjxxx6xz3F5YrpxmSiPs7SQOzveezZrUeDIHbeeZ/bfI5WvtSBm2fFt7ccOkeiYH00WuG2gdM8ibUuZz41EKOa+q2sunw2I2Iph9LJhA7zBVOtIEIs2yoYJRB4e6n3kbQPDQh4pobsBIS3QsUzu2yhkKluveSyOW4xRdU4W+YPz8SHUoj6SceUnUzYun7zWD8WnkzyzDOfetJwNOthliwbCbq2EEBl85ryrWqbkFs8nUVfOv8S2zIs+g/sVRKi6zxFa7hBHNK71EPsKMdMj7+cKQjbaK0w21D/1g==
    user: AgCxA8qxNgCOoR74u7yAowZUCwbjqOh+j6tvWEz8qINQB4t5WbEyTiJ9blFKzuFIcsDEr7yvaR239ntTFM4kbVyk8mwnedmC23R2Qpe8vD9yRW1eIxsWgVuVWw74Ck69o4ejyruJXgYTLdAyE7cgJifEi8JtivUAUWMpB6YdCAoVxGIn+NHj0OklbiVrrslvaKueSjhqHH4o5FDFsNS29DW8jROklsH70zfMZWTwTNw5GjCz2/q06Wt11lggYDSmnhjarw3F4VL4eIq+mFwBgiMPabP3GG0NlUVawy3rEjdaJfPkknF6zz3jScYEKmmytMPt/H6qlSDymVn2UjE+ThsaQDmqkse/pg4YlW6Ty0MsFfkF/fe2yzzjUUoQ9o4Qs1nnOWDyFPPU07C5V8iHO6SY9omgdGh3CNvHJNybyJQ6htkd/z82X+lRtVBOwWIwXvASxZpHFxyMdtD6qbcUx8ofLllWK3fIOoUMr8jE6/7H/s2utA0KUUcWsTwo0vSTRk3BoORmVt+yS2xTfpI6nu9QLo/gGwkFBiZrM19sMoiwRNsEiNAHnf5voZRA85mRx8LRoLr585sHYK4JQymzKBuAFUV0QN0aJgTiQ20c7PmdXxlbwpS+V+WxH6i/l1TJjsNIjSV1KkNDnsMbmoxDEuuHr+7fTHT4mFWLGcuL0DjKtNQ7CDKVN9gob3wk+WEcaBOGdTHm
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:database: {}
            f:password: {}
            f:root-password: {}
            f:user: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2020-11-14T15:38:50Z"
      name: zuul-mysql
      namespace: zuul
    type: Opaque

